### ISSUE TITLE
[1.12.2] Memory Leaks

### ISSUE THREAD

**Issue by Ghostlyr** [dragon-forge/HammerLib#12]
I have installed Botanic Additions (12.2.6) and this library (2.0.6.32) in my modpack and now I have "OutOfMemoryError" client crashes every few hours of play

```
java.lang.OutOfMemoryError: Java heap space
    at it.unimi.dsi.fastutil.ints.IntArrays.grow(IntArrays.java:263)
    at it.unimi.dsi.fastutil.ints.IntArrayList.grow(IntArrayList.java:308)
    at it.unimi.dsi.fastutil.ints.IntArrayList.add(IntArrayList.java:322)
    at it.unimi.dsi.fastutil.ints.AbstractIntList.push(AbstractIntList.java:430)
    at com.zeitheron.hammercore.client.render.shader.GlShaderStack.glsPushShader(GlShaderStack.java:28)
    at com.zeitheron.hammercore.client.utils.ItemColorHelper.renderItemModelIntoGUIPre(ItemColorHelper.java:56)
    at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java)
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:559)
    at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:356)
    at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1248)
    at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:611)
    at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:346)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:142)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1426)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at java.lang.invoke.LambdaForm$DMH/254413710.invokeStaticInit_L_V(LambdaForm$DMH)
    at java.lang.invoke.LambdaForm$BMH/487694075.reinvoke(LambdaForm$BMH)
    at java.lang.invoke.LambdaForm$MH/1773283386.invoker(LambdaForm$MH)
    at java.lang.invoke.LambdaForm$MH/739498517.invokeExact_MT(LambdaForm$MH)
    at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
```

![image](https://user-images.githubusercontent.com/8511068/172067853-d12a6fca-89e2-47c8-bf21-8290deaa2377.png)

I have a memory dump if you need. Let me know your email address where I can send it.

**Comment by MissPotato** [comment]
Offtopic but: what tool do you use to view heapdumps like this? Everything I've used has just blamed forge itself.

**Comment by fivekWBassMachine** [comment]
@MissPotato the screenshot above should be [VisualVM](https://visualvm.github.io/). For finding Mods which cause long ticks ans such stuff, I'm currently using [Spark](https://www.curseforge.com/minecraft/mc-mods/spark); a Minecraft mod. Specially the command `/spark profiler --start` and `... --stop`. (The other commands are useful too)

**Comment by Zeitheron** [comment]
I added a clearing mechanism to hopefully resolve this issue for good.
