### ISSUE TITLE
[1.12.2]12.2.51 stucks loading for about 3 minutes

### ISSUE THREAD

**Issue by ghost** [dragon-forge/HammerLib#66]
Please do not perform network activity on the main thread, or at least provide an option to disable the connection
related logs
```
[17:12:35] [Client thread/INFO] [tconevo-core]: Applying transform "Modify Melt Speed" to class: slimeknights.tconstruct.smeltery.tileentity.TileHeatingStructure
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: com.zeitheron.hammercore.lib.zlib.web.HttpRequest$HttpRequestException: javax.net.ssl.SSLException: Read timed out
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.code(HttpRequest.java:1628)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.stream(HttpRequest.java:1965)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.buffer(HttpRequest.java:1952)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.body(HttpRequest.java:1858)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.body(HttpRequest.java:1876)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter.<clinit>(ModSourceAdapter.java:149)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.zeitheron.hammercore.utils.CommonMessages.printMessageOnIllegalRedistribution(CommonMessages.java:17)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.zeitheron.hammercore.HammerCore.<init>(HammerCore.java:134)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at java.lang.Class.newInstance(Class.java:442)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraftforge.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:191)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:599)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandlerMixin.java:232)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraft.client.Minecraft.func_71384_a(MinecraftMixin.java:467)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraft.client.Minecraft.func_99999_d(MinecraftMixin.java:6101)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[17:15:37] [Client thread/INFO] [STDERR]: [com.zeitheron.hammercore.utils.java.io.win32.ModSourceAdapter:<clinit>:158]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: javax.net.ssl.SSLException: Read timed out
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1952)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1947)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.security.AccessController.doPrivileged(Native Method)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1946)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1516)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1492)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.security.AccessController.doPrivileged(Native Method)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.code(HttpRequest.java:1625)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	... 52 more
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: Caused by: javax.net.ssl.SSLException: Read timed out
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.security.ssl.Alert.createSSLException(Alert.java:127)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:331)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:274)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:138)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1492)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at java.security.AccessController.doPrivileged(Native Method)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:784)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3067)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderField(HttpsURLConnectionImpl.java:305)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.header(HttpRequest.java:2268)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.parameter(HttpRequest.java:2373)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.zeitheron.hammercore.lib.zlib.web.HttpRequest.charset(HttpRequest.java:2489)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	... 49 more
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	Suppressed: java.net.SocketException: Connection reset by peer: socket write error
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 		at java.net.SocketOutputStream.socketWrite0(Native Method)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 		at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 		at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 		at sun.security.ssl.TransportContext.fatal(TransportContext.java:362)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 		... 69 more
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: Caused by: java.net.SocketTimeoutException: Read timed out
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at java.net.SocketInputStream.socketRead0(Native Method)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:109)
[17:15:37] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:668]: 	... 66 more
[17:15:37] [Client thread/INFO] [HammerLib]: Added particle lighting supplier
[17:15:37] [Client thread/INFO] [HammerLib]: Applied @SimplyRegister to org.zeith.hammerlib.core.init.SourceTypesHL, which belongs to hammercore (HammerLib)
[17:15:37] [Client thread/INFO] [HammerLib]: Applied @SimplyRegister to com.zeitheron.hammercore.internal.init.ItemsHC, which belongs to hammercore (HammerLib)
[17:15:37] [Client thread/INFO] [HammerLib]: Applied @SimplyRegister to com.zeitheron.hammercore.internal.init.BlocksHC, which belongs to hammercore (HammerLib)
```

**Comment by PinkGoosik** [comment]
Stumbled upon this, this so stupid

**Comment by Krutoy242** [comment]
Does this issue may be related to https://github.com/dragon-forge/HammerLib/issues/54 ?

**Comment by 1tsukusu** [comment]
> Does this issue may be related to [#54](https://github.com/dragon-forge/HammerLib/issues/54) ?

i think yes, i have the same exact problem, zapret does not work to fix this for some reason.
