### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.zeith.hammerlib.HammerLib

### ISSUE THREAD

**Issue by Oleksandr-Hlushchenko** [dragon-forge/HammerLib#68]
Forge 1.19.2
HammerLib-1.19.2-19.3.82

```// You're mean.

Time: 2024-08-16 15:41:34
Description: Initializing game

java.lang.NoClassDefFoundError: Could not initialize class org.zeith.hammerlib.HammerLib
	at org.zeith.hammerlib.proxy.HLConstants.<clinit>(HLConstants.java:12) ~[HammerLib-1.19.2-19.3.82.jar%23358!/:19.3.82] {re:classloading}
	at org.zeith.hammerlib.client.render.RenderCustomGlint.<clinit>(RenderCustomGlint.java:23) ~[HammerLib-1.19.2-19.3.82.jar%23358!/:19.3.82] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.RenderBuffers.handler$zen000$addGlint_1_19_2(RenderBuffers.java:1029) ~[client-1.19.2-20220805.130853-srg.jar%23432!/:?] {re:mixin,re:classloading,pl:mixin:APP:enchantedbookredesign.mixins.json:RenderTypeBuffersMixin,pl:mixin:APP:mixins.hammerlib.json:client.render.RenderBuffersMixin,pl:mixin:APP:botania_xplat.mixins.json:client.RenderBuffersAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.RenderBuffers.m_110101_(RenderBuffers.java) ~[client-1.19.2-20220805.130853-srg.jar%23432!/:?] {re:mixin,re:classloading,pl:mixin:APP:enchantedbookredesign.mixins.json:RenderTypeBuffersMixin,pl:mixin:APP:mixins.hammerlib.json:client.render.RenderBuffersMixin,pl:mixin:APP:botania_xplat.mixins.json:client.RenderBuffersAccessor,pl:mixin:A}
	at net.minecraft.client.renderer.RenderBuffers.m_110099_(RenderBuffers.java:28) ~[client-1.19.2-20220805.130853-srg.jar%23432!/:?] {re:mixin,re:classloading,pl:mixin:APP:enchantedbookredesign.mixins.json:RenderTypeBuffersMixin,pl:mixin:APP:mixins.hammerlib.json:client.render.RenderBuffersMixin,pl:mixin:APP:botania_xplat.mixins.json:client.RenderBuffersAccessor,pl:mixin:A}
	at net.minecraft.Util.m_137469_(Util.java:368) ~[client-1.19.2-20220805.130853-srg.jar%23432!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.UtilMixin,pl:mixin:A}
	at net.minecraft.client.renderer.RenderBuffers.<init>(RenderBuffers.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23432!/:?] {re:mixin,re:classloading,pl:mixin:APP:enchantedbookredesign.mixins.json:RenderTypeBuffersMixin,pl:mixin:APP:mixins.hammerlib.json:client.render.RenderBuffersMixin,pl:mixin:APP:botania_xplat.mixins.json:client.RenderBuffersAccessor,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:504) ~[client-1.19.2-20220805.130853-srg.jar%23432!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:customskinloader:MinecraftTransformer,xf:fml:xaerominimap:xaero_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,xf:fml:customskinloader:MinecraftTransformer,xf:fml:xaerominimap:xaero_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23432!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23432!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.7.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23124!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23124!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23124!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23124!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23124!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23124!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23124!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at launcher.cOM1.aux(SourceFile:319) [McSkillTest.jar:?] {}
	at launcher.cOM1.main(SourceFile:201) [McSkillTest.jar:?] {}
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NullPointerException [in thread "modloading-worker-0"]
	at org.zeith.hammerlib.util.mcf.ScanDataHelper.lambda$lookupAnnotatedObjects$3(ScanDataHelper.java:51) ~[HammerLib-1.19.2-19.3.82.jar%23358!/:19.3.82] {re:classloading}
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?] {}
	at org.zeith.hammerlib.util.mcf.ScanDataHelper.lookupAnnotatedObjects(ScanDataHelper.java:53) ~[HammerLib-1.19.2-19.3.82.jar%23358!/:19.3.82] {re:classloading}
	at org.zeith.hammerlib.util.mcf.ScanDataHelper.lookupAnnotatedObjects(ScanDataHelper.java:43) ~[HammerLib-1.19.2-19.3.82.jar%23358!/:19.3.82] {re:classloading}
	at org.zeith.hammerlib.compat.base.CompatList.gather(CompatList.java:93) ~[HammerLib-1.19.2-19.3.82.jar%23358!/:19.3.82] {re:classloading,re:mixin}
	at org.zeith.hammerlib.compat.base.CompatList.gather(CompatList.java:66) ~[HammerLib-1.19.2-19.3.82.jar%23358!/:19.3.82] {re:classloading,re:mixin}
	at org.zeith.hammerlib.HammerLib.<clinit>(HammerLib.java:53) ~[HammerLib-1.19.2-19.3.82.jar%23358!/:19.3.82] {re:classloading,re:mixin}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.19.2-43.3.7.jar%23434!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:122) ~[fmlcore-1.19.2-43.3.7.jar%23433!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}
```

**Comment by Zeitheron** [comment]
Any more info, please?

Like, what mods may be causing this issue?
