### ISSUE TITLE
Cant load into minecraft sever I keep  crashing 

### ISSUE THREAD

**Issue by Mexinos** [dragon-forge/HammerLib#70]
Below you see my Report, I am but a simple humble Pixlemon enjoyer.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  HCASM (HammerLib-1.12.2-12.2.56.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 10/15/24 9:58 PM
Description: Unexpected error

java.lang.IllegalStateException: Ingredient Filter has not been created yet.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at mezz.jei.Internal.getIngredientFilter(Internal.java:88)
	at mezz.jei.startup.ProxyCommonClient.onClientTick(ProxyCommonClient.java:133)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_346_ProxyCommonClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at mezz.jei.Internal.getIngredientFilter(Internal.java:88)
	at mezz.jei.startup.ProxyCommonClient.onClientTick(ProxyCommonClient.java:133)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_346_ProxyCommonClient_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['kikirin'/22, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['kikirin'/22, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2843029944 bytes (2711 MB) / 3605528576 bytes (3438 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                | Source                                        | Signature                                |
	|:------ |:------------------- |:---------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                 | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42                   | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99              | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2860           | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | hammercore          | 12.2.56                | HammerLib-1.12.2-12.2.56.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | hammermetals        | 15r                    | HammerMetals-1.12.2-15r.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | apsrepowered        | 12.1.6                 | APSRepowered-1.12.2-12.1.6.jar                | None                                     |
	| LCHIJA | biomesoplenty       | 7.0.1.2444             | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| LCHIJA | bop_patch           | 1.0                    | BOP-Patch-1.0.jar                             | None                                     |
	| LCHIJA | konkrete            | 1.0.3                  | konkrete_1.0.3_MC_1.12-1.12.2.jar             | None                                     |
	| LCHIJA | fancymenu           | 1.5.2                  | fancymenu_1.5.2_MC_1.12-1.12.2.jar            | None                                     |
	| LCHIJA | pixelmon            | 8.4.3                  | Pixelmon-1.12.2-8.4.3-universal.jar           | None                                     |
	| LCHIJA | gameshark           | 6.0.6                  | Gameshark-1.12.2-6.0.6-universal.jar          | None                                     |
	| LCHIJA | jei                 | 4.7.11.102             | jei_1.12.2-4.7.11.102.jar                     | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.7.1           | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHIJA | naturescompass      | 1.8.5                  | NaturesCompass-1.12.2-1.8.5.jar               | None                                     |
	| LCHIJA | pixelextras         | 2.5.17                 | PixelExtras-1.12.2-2.5.17-universal.jar       | None                                     |
	| LCHIJA | tcg                 | 1.12.2-8.4.3-universal | Pixelmon-1.12.2-8.4.3-universal.jar           | None                                     |
	| LCHIJA | refinedstorage      | 1.6.16                 | refinedstorage-1.6.16.jar                     | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | travelersbackpack   | 1.0.35                 | TravelersBackpack-1.12.2-1.0.35.jar           | None                                     |
	| LCHIJA | veinminer           | 0.38.2                 | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |
	| LCHIJA | veinminermodsupport | 0.38.2                 | VeinMiner-1.12-0.38.2.647+b31535a.jar         | None                                     |

	Loaded coremods (and transformers): 
HCASM (HammerLib-1.12.2-12.2.56.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 565.90' Renderer: 'NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2'
	HammerLib Debug Information: 
		Dependent Mods:
			-Hammer Metals (hammermetals) @ 15r
			-Advanced Power Systems: Repowered (apsrepowered) @ 12.1.6

	Launched Version: forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 565.90, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, file/ThePixelmonOST.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700K

**Comment by Zeitheron** [comment]
```
java.lang.IllegalStateException: Ingredient Filter has not been created yet.
at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
at mezz.jei.Internal.getIngredientFilter(Internal.java:88)
at mezz.jei.startup.ProxyCommonClient.onClientTick(ProxyCommonClient.java:133)
```
